### ISSUE TITLE
Sugiro colocar as informações do seu projeto no README

### ISSUE THREAD

**Issue by MatheusAlvarez** [RodrigoAnjos2004/Street-Fighter-Selection#1]
Seu projeto ficou muito top, porém acho que para dar um up nele você poderia descreve-lo no readme, explicar as características principais, como fazer para funcionar, linguagens utilizadas e outros.

exemplo: https://github.com/acenelio/exemplo-readme

**Comment by RodrigoAnjos2004** [comment]
simmm! Vou fazer.
